version: 2

references:
  # References to manage the dependency cache
  restore_bundle_cache: &restore_bundle_cache
    restore_cache:
      keys:
        - bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "discordrb.gemspec" }}
        - bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}
        - bundle-cache-v1-{{ checksum "ruby_version.txt" }}
  save_bundle_cache: &save_bundle_cache
    save_cache:
      key: bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "discordrb.gemspec" }}
      paths:
        - ./vendor/bundle

  # Typical job filters for running builds on all branches and tags
  test_filters: &test_filters
    branches:
      only: /.*/
    tags:
      only: /^v.*/

  # Installs misc OS packages needed in Alpine containers
  install_packages: &install_packages
    run:
      name: Install OS packages
      command: apk add git build-base ruby-dev ruby-etc ruby-json

  # Installs dependencies
  install_dependencies: &install_dependencies
      run:
        name: Install dependencies
        command: bundle install --path vendor/bundle

  # Displays the Ruby version, and writes it to ruby_version.txt
  ruby_version: &ruby_version
    run:
      name: Ruby version
      command: |
        ruby -v
        echo $RUBY_VERSION > ruby_version.txt

  # General steps to run specs against a Ruby version
  test_ruby: &test_ruby
    - *install_packages
    - checkout
    - *ruby_version
    - *restore_bundle_cache
    - *install_dependencies
    - *save_bundle_cache
    - run:
        name: Run RSpec
        command: bundle exec rspec

jobs:
  test_ruby_24:
    docker:
      - image: ruby:2.4-alpine
    steps: *test_ruby

  test_ruby_25:
    docker:
      - image: ruby:2.5-alpine
    steps: *test_ruby

  test_ruby_26:
    docker:
      - image: ruby:2.6-alpine
    steps: *test_ruby

  rubocop:
    docker:
      - image: ruby:2.5-alpine
    steps:
      - *install_packages
      - checkout
      - *ruby_version
      - *restore_bundle_cache
      - *install_dependencies
      - *save_bundle_cache
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

  yard:
    docker:
      - image: ruby:2.5-alpine
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - *install_packages
      - checkout
      - *ruby_version
      - *restore_bundle_cache
      - *install_dependencies
      - *save_bundle_cache
      - run:
          name: Run YARD
          command: bundle exec yard --output-dir /tmp/workspace/docs
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docs

  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Clone docs
          command: git clone --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/discordrb.git -b gh-pages .
      - run:
          name: Push updated docs
          command: |
            git config user.name "Circle CI"
            git config user.email "zachnowicki@gmail.com"

            SOURCE_BRANCH=$CIRCLE_BRANCH
            if [ -n "$CIRCLE_TAG" ]; then
              SOURCE_BRANCH=$CIRCLE_TAG
            fi

            mkdir -p $SOURCE_BRANCH
            rm -r $SOURCE_BRANCH/*
            cp -r /tmp/workspace/docs/. ./$SOURCE_BRANCH/

            git add $SOURCE_BRANCH
            git commit --allow-empty -m "Deploy docs"
            git push -q https://${DOCS_GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/discordrb.git

workflows:
  version: 2
  ci:
    jobs:
      # Test Ruby platforms:
      - test_ruby_24:
          filters: *test_filters
      - test_ruby_25:
          filters: *test_filters
      - test_ruby_26:
          filters: *test_filters
      - rubocop:
          filters: *test_filters
      - yard:
          filters: *test_filters

      # Deploy GitHub pages if all jobs pass on master branch or a tag:
      - deploy:
          requires:
            - test_ruby_24
            - test_ruby_25
            - test_ruby_26
            - rubocop
            - yard
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
